=head1 NAME

Chiffon - Web application framework for PSGI/Plack

=head1 SYNOPSIS

  chiffon.pl -p MyApp;

=head1 DESCRIPTION

Chiffon is web application framework for PSGI/Plack

=head1 AUTHOR

Nishibayashi Takuji E<lt>takuji {at} senchan.jpE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

